---
name: Elevator
main: matcracker\Elevator\Main
version: 1.1.0
api: 4.0.0

author: matcracker
description: "A simple elevator plugin that uses signs."
website: https://github.com/matcracker/Elevator

commands:
  elevator:
    permission: "elevator.command.reload"
    description: "Allows to reload the Elevator plugin configuration"
    usage: "/elevator reload"

permissions:
  elevator.command.reload:
    default: op
  elevator.sign.create:
    default: op
  elevator.sign.use:
    default: true
...